---
title: "Evaluating Ab and Kp Models"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Load Libraries

```{r loadLibraries, results = "hide", echo = FALSE}
library(plyr, quietly = T)
library(tidyverse, quietly = T)
library(MALDIquant, quietly = T)
library(MALDIquantForeign, quietly = T)
library(caret, quietly = T)
library(PRROC, quietly = T)
library(stringr, quietly = T)
library(forcats, quietly = T)
library(doParallel, quietly = T)

source("R/preProcessSpec.R")
source("R/extract.R")
source("R/ggplotTheme.R")

set.seed(73239)                        # For reproducibility
```

# Load Models and Test Set

```{r loadModels}
modelList <- readRDS("results/modelList.RDS")

testSets <- readRDS("temp/testDatList.RDS")
```

```{r AbModels}
AbRes <- tibble(obs = testSets$AbRes$AbRes)
AbRes$pred <- predict(modelList[[1]], testSets$AbRes)
p <- predict(modelList[[1]], testSets$AbRes, type = "prob")
AbRes <- cbind(AbRes, p)

confusionMatrix(data = AbRes$pred, reference = AbRes$obs, positive = "pos")

AbResPR <- pr.curve(AbRes$pos[AbRes$obs == "pos"], 
                    AbRes$pos[AbRes$obs == "neg"], curve = T)

AbResROC <- roc.curve(AbRes$pos[AbRes$obs == "pos"], 
                      AbRes$pos[AbRes$obs == "neg"], curve = T)

# Susceptible
AbSus <- tibble(obs = testSets$AbSus$AbSus)
AbSus$pred <- predict(modelList[[2]], testSets$AbSus)
p <- predict(modelList[[2]], testSets$AbSus, type = "prob")
AbSus <- cbind(AbSus, p)

confusionMatrix(data = AbSus$pred, reference = AbSus$obs, positive = "pos")

AbSusPR <- pr.curve(AbSus$pos[AbSus$obs == "pos"], 
                    AbSus$pos[AbSus$obs == "neg"], curve = T)

AbSusROC <- roc.curve(AbSus$pos[AbSus$obs == "pos"], 
                      AbSus$pos[AbSus$obs == "neg"], curve = T)
```

```{r KpModels}
KpRes <- tibble(obs = testSets$KpRes$KpRes)
KpRes$pred <- predict(modelList[[3]], testSets$KpRes)
p <- predict(modelList[[3]], testSets$KpRes, type = "prob")
KpRes <- cbind(KpRes, p)

confusionMatrix(data = KpRes$pred, reference = KpRes$obs, positive = "pos")

KpResPR <- pr.curve(KpRes$pos[KpRes$obs == "pos"], 
                    KpRes$pos[KpRes$obs == "neg"], curve = T)

KpResROC <- roc.curve(KpRes$pos[KpRes$obs == "pos"], 
                      KpRes$pos[KpRes$obs == "neg"], curve = T)

KpSus <- tibble(obs = testSets$KpSus$KpSus)
KpSus$pred <- predict(modelList[[4]], testSets$KpSus)
p <- predict(modelList[[4]], testSets$KpSus, type = "prob")
KpSus <- cbind(KpSus, p)

confusionMatrix(data = KpSus$pred, reference = KpSus$obs, positive = "pos")

KpSusPR <- pr.curve(KpSus$pos[KpSus$obs == "pos"], 
                    KpSus$pos[KpSus$obs == "neg"], curve = T)

KpSusROC <- roc.curve(KpSus$pos[KpSus$obs == "pos"], 
                      KpSus$pos[KpSus$obs == "neg"], curve = T)
```

# Plot Curves
```{r plotAb}
prnames <- c("Recall", "Precision", "threshold")
prAb <- as.tibble(rbind(AbResPR$curve, AbSusPR$curve))
names(prAb) <- prnames

labsAb <- c(paste0("Resistant, AUC = ", round(AbResPR$auc.integral, 2)),
            paste0("Susceptible, AUC = ", round(AbSusPR$auc.integral, 2)))

prAb %>%
    mutate(cond = c(rep(labsAb[1], nrow(AbResPR$curve)),
                    rep(labsAb[2], nrow(AbSusPR$curve)))) %>%
    ggplot(aes(x = Recall, y = Precision, color = cond)) +
    geom_path(size = 1) + 
    coolTheme +
    theme(legend.position = c(0.05,0.05),
          legend.justification = c(0,0),
          legend.title = element_blank()) +
    coord_equal() +
    ggtitle("Precision-Recall")

ggsave("results/AbPrCurve.png", width = 3.5, height = 3.5)


# ROC
rocnames <- c("1 - Specificity", "Sensitivity", "threshold")
rocAb <- as.tibble(rbind(AbResROC$curve, AbSusROC$curve))
names(rocAb) <- rocnames

labsAb2 <- c(paste0("Resistant, AUC = ", round(AbResROC$auc, 2)),
             paste0("Susceptible, AUC = ", round(AbSusROC$auc, 2)))

rocAb %>%
    mutate(cond = c(rep(labsAb2[1], nrow(AbResROC$curve)),
                    rep(labsAb2[2], nrow(AbSusROC$curve)))) %>%
    ggplot(aes(x = `1 - Specificity`, y = Sensitivity, color = cond)) +
    geom_path(size = 1) + 
    coolTheme +
    theme(legend.position = c(0.95,0.05),
          legend.justification = c(1,0),
          legend.title = element_blank()) +
    coord_equal() +
    ggtitle("ROC")

ggsave("results/AbRocCurve.png", width = 3.5, height = 3.5)
```

```{r plotKp}
prKp <- as.tibble(rbind(KpResPR$curve, KpSusPR$curve))
names(prKp) <- prnames

labsKp <- c(paste0("Resistant, AUC = ", round(KpResPR$auc.integral, 2)),
            paste0("Susceptible, AUC = ", round(KpSusPR$auc.integral, 2)))

prKp %>%
    mutate(cond = c(rep(labsKp[1], nrow(KpResPR$curve)),
                    rep(labsKp[2], nrow(KpSusPR$curve)))) %>%
    ggplot(aes(x = Recall, y = Precision, color = cond)) +
    geom_path(size = 1) + 
    coolTheme +
    theme(legend.position = c(0.05,0.05),
          legend.justification = c(0,0),
          legend.title = element_blank()) +
    coord_equal() +
    ggtitle("Precision-Recall")

ggsave("results/KpPrCurve.png", width = 3.5, height = 3.5)


# ROC
rocKp <- as.tibble(rbind(KpResROC$curve, KpSusROC$curve))
names(rocKp) <- rocnames

labsKp2 <- c(paste0("Resistant, AUC = ", round(KpResROC$auc, 2)),
             paste0("Susceptible, AUC = ", round(KpSusROC$auc, 2)))

rocKp %>%
    mutate(cond = c(rep(labsKp2[1], nrow(KpResROC$curve)),
                    rep(labsKp2[2], nrow(KpSusROC$curve)))) %>%
    ggplot(aes(x = `1 - Specificity`, y = Sensitivity, color = cond)) +
    geom_path(size = 1) + 
    coolTheme +
    theme(legend.position = c(0.95,0.05),
          legend.justification = c(1,0),
          legend.title = element_blank()) +
    coord_equal() +
    ggtitle("ROC")

ggsave("results/KpRocCurve.png", width = 3.5, height = 3.5)
```

# Evaluate Complex Spectra

```{r}
complexSpec <- readRDS("temp/complexFeatures.RDS")

cAbRes <- tibble(obs = complexSpec$AbRes)
cAbRes$pred <- predict(modelList[[1]], complexSpec, type = "raw")

p <- predict(modelList[[1]], complexSpec, type = "prob")
cAbRes <- cbind(cAbRes, p)

confusionMatrix(data = cAbRes$pred, reference = cAbRes$obs, positive = "pos")

cAbResPR <- pr.curve(cAbRes$pos[cAbRes$obs == "pos"], 
                     cAbRes$pos[cAbRes$obs == "neg"], curve = T)

cAbResROC <- roc.curve(cAbRes$pos[cAbRes$obs == "pos"], 
                       cAbRes$pos[cAbRes$obs == "neg"], curve = T)



cAbRes <- cbind(cAbRes, select(complexSpec, n, AbResCoeff))

cAbResSumm <- cAbRes %>%
  group_by(n) %>%
  do(pr = pr.curve(.$pos[.$obs == "pos"], .$pos[.$obs == "neg"]),
     roc = roc.curve(.$pos[.$obs == "pos"], .$pos[.$obs == "neg"])) %>%
  mutate(prAUC = pr$auc.integral,
         rocAUC = roc$auc,
         ex = "Ab Resistant")

# Susceptible
cAbSus <- tibble(obs = complexSpec$AbSus)
cAbSus$pred <- predict(modelList[[2]], complexSpec, type = "raw")
p <- predict(modelList[[2]], complexSpec, type = "prob")
cAbSus <- cbind(cAbSus, p)

confusionMatrix(data = cAbSus$pred, reference = cAbSus$obs, positive = "pos")

cAbSusPR <- pr.curve(cAbSus$pos[cAbSus$obs == "pos"], 
                     cAbSus$pos[cAbSus$obs == "neg"], curve = T)

cAbSusROC <- roc.curve(cAbSus$pos[cAbSus$obs == "pos"], 
                       cAbSus$pos[cAbSus$obs == "neg"], curve = T)


cAbSus <- cbind(cAbSus, select(complexSpec, n, AbSusCoeff))

cAbSusSumm <- cAbSus %>%
  group_by(n) %>%
  do(pr = pr.curve(.$pos[.$obs == "pos"], .$pos[.$obs == "neg"]),
     roc = roc.curve(.$pos[.$obs == "pos"], .$pos[.$obs == "neg"])) %>%
  mutate(prAUC = pr$auc.integral,
         rocAUC = roc$auc,
         ex = "Ab Susceptible")
```

```{r}
cKpRes <- tibble(obs = complexSpec$KpRes)
cKpRes$pred <- predict(modelList[[3]], complexSpec, type = "raw")

p <- predict(modelList[[3]], complexSpec, type = "prob")
cKpRes <- cbind(cKpRes, p)

confusionMatrix(data = cKpRes$pred, reference = cKpRes$obs, positive = "pos")

cKpResPR <- pr.curve(cKpRes$pos[cKpRes$obs == "pos"], 
                     cKpRes$pos[cKpRes$obs == "neg"], curve = T)

cKpResROC <- roc.curve(cKpRes$pos[cKpRes$obs == "pos"], 
                       cKpRes$pos[cKpRes$obs == "neg"], curve = T)

cKpRes <- cbind(cKpRes, select(complexSpec, n, KpResCoeff))

cKpResSumm <- cKpRes %>%
  group_by(n) %>%
  do(pr = pr.curve(.$pos[.$obs == "pos"], .$pos[.$obs == "neg"]),
     roc = roc.curve(.$pos[.$obs == "pos"], .$pos[.$obs == "neg"])) %>%
  mutate(prAUC = pr$auc.integral,
         rocAUC = roc$auc,
         ex = "Kp Resistant")


# Susceptible
cKpSus <- tibble(obs = complexSpec$KpSus)
cKpSus$pred <- predict(modelList[[4]], complexSpec, type = "raw")
p <- predict(modelList[[4]], complexSpec, type = "prob")
cKpSus <- cbind(cKpSus, p)

confusionMatrix(data = cKpSus$pred, reference = cKpSus$obs, positive = "pos")

cKpSusPR <- pr.curve(cAbSus$pos[cKpSus$obs == "pos"], 
                     cAbSus$pos[cKpSus$obs == "neg"], curve = T)

cKpSusROC <- roc.curve(cAbSus$pos[cKpSus$obs == "pos"], 
                       cAbSus$pos[cKpSus$obs == "neg"], curve = T)

cKpSus <- cbind(cKpSus, select(complexSpec, n, KpSusCoeff))

cKpSusSumm <- cKpSus %>%
  group_by(n) %>%
  do(pr = pr.curve(.$pos[.$obs == "pos"], .$pos[.$obs == "neg"]),
     roc = roc.curve(.$pos[.$obs == "pos"], .$pos[.$obs == "neg"])) %>%
  mutate(prAUC = pr$auc.integral,
         rocAUC = roc$auc,
         ex = "Kp Susceptible")
```

```{r}

nFullSumm <- select(cAbResSumm, -pr, -roc) %>%
  full_join(select(cAbSusSumm, -pr, -roc)) %>%
  full_join(select(cKpResSumm, -pr, -roc)) %>%
  full_join(select(cKpSusSumm, -pr, -roc))

nFullSumm %>%
  ggplot(aes(x = n, y = prAUC, group = ex, color = ex)) +
  geom_line() +
  geom_point() +
  coolTheme +
  theme(legend.title = element_blank()) +
  ylab("Precision-Recall AUC") +
  xlab("Species in Mixture Spectrum") +
  ylim(c(0, 1))

ggsave("results/complexPR.png", width = 5.5, height = 3.5)

nFullSumm %>%
  ggplot(aes(x = n, y = rocAUC, group = ex, color = ex)) +
  geom_line() +
  geom_point() +
  coolTheme +
  theme(legend.title = element_blank()) +
  ylab("ROC AUC") +
  xlab("Species in Mixture Spectrum") +
  ylim(c(0, 1))


ggsave("results/complexROC.png", width = 5.5, height = 3.5)

```
# Exploring problems with the Ab mixture model

```{r AbInDepth}
mxFeatures <- readRDS("temp/comboFeatTbl.RDS")

predRes <- cbind(cAbRes, complexSpec$id) %>%
    rename(spec_id = `complexSpec$id`)

resPeak <- mxFeatures %>% filter(feat == "mz2036.4937") %>%
    left_join(predRes) %>%
    mutate(correct = (obs == pred),
           relInt = relInt * 100,
           Resistance = as.factor(ifelse(obs == "pos", "Yes", "No")),
           Resistance = fct_rev(Resistance))


resPeak %>%
    ggplot(aes(x = real_mz, y = relInt, color = Resistance)) +
    geom_point() +
    coolTheme +
    xlab("m/z") +
    ylab("Relative Intensity") +
    theme(legend.position = c(0.95, 0.95),
          legend.justification = c(1, 1))

ggsave("results/AbComplex2033.png", width = 5, height = 2.5)

resPeak %>%
    ggplot(aes(x = real_mz, color = Resistance, fill = Resistance)) +
    geom_density(alpha = 0.5) +
    coolTheme +
    xlab("m/z") +
    ylab("Density") +
    theme(legend.position = c(0.95, 0.95),
          legend.justification = c(1, 1))

ggsave("results/AbComplex2033Density.png", width = 5, height = 2.25)

mxInfo <- readRDS("temp/complexComponents.RDS")

mxInfo <- mxInfo %>%
    left_join(predRes) %>%
    select(spec_id, obs, pred, type)

fdrSumm <- mxInfo %>%
    filter(obs == "neg", obs != pred) %>%
    group_by(type) %>%
    summarise(count = length(pred)) %>%
    arrange(desc(count))



smFile <- list.files("data/fullLib/Salmonella minnesota", pattern = ".mzXML", full.names = T)[2]
smSpec <- preProcessSpec(smFile, hws = 80)
smSpecDat <- map_df(smSpec, extractSpectra)

smSpecNorm <- smSpecDat %>%
  group_by(mz) %>%
  summarize(relInt = sum(relInt)) %>%
  ungroup() %>%
  mutate(relInt = relInt / max(relInt) * 100,
         type = "combined",
         id = "combined")

smSpecNorm %>%
  ggplot(aes(x = as.numeric(mz), y = relInt)) +
  geom_vline(xintercept = 2036.4937, color = "blue", linetype = "dashed") +
  geom_line(size = 0.5) +
  coolTheme +
  theme(legend.position = "none") +
  labs(title = "Salmonella Minnesota",
       x = "m/z",
       y = "Relative Intensity")

ggsave("results/salmonellaMinnesotaSpec.png", width = 5, height = 2.25)

smSpecNorm %>%
  ggplot(aes(x = as.numeric(mz), y = relInt)) +
  geom_line(size = 1) +
  coolTheme +
  theme(legend.position = "none") +
  labs(x = "m/z",
       y = "Relative Intensity",
       title = "Salmonella Minnesota") +
  xlim(c(min(resPeak$real_mz), max(resPeak$real_mz))) +
  ylim(c(0, 15))

ggsave("results/smSpecZoom.png", width = 5, height = 2.5)
```

