---
title: "Building Models From Glycolipid MALDI-TOF-MS Extracted From Pure Culture"
Author: "William E Fondrie"
Date: "4/9/17"
output: github_document
---


```{r setup, include = F}
knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(warning = F, message = F)
```

```{r loadLibraries, results = "hide", echo = F}
library(plyr, quietly = T)
library(tidyverse, quietly = T)
library(MALDIquant, quietly = T)
library(MALDIquantForeign, quietly = T)
library(caret, quietly = T)
library(PRROC, quietly = T)
library(stringr, quietly = T)
library(doParallel, quietly = T)

source("R/preProcessSpec.R")
source("R/extract.R")

set.seed(1832939)                        # For reproducibility

cl <- makeCluster(detectCores() - 1)       # For parallelization
registerDoParallel(cl)
```


## Load Mass Spectra and Extract Peaks
```{r importData}
files <- list.files("data/fullLib", 
                    full.names = T, 
                    pattern = "mzXML$",
                    recursive = T)
#files <- sample(files, 50)

specInfo <- tibble(fname = files) %>%
    mutate(type = str_match(fname, "([^\\^/]+)[\\/][^\\^/]+mzXML$")[ , 2],
           id = str_match(fname, "([^\\^/]+).mzXML$")[ , 2],
           AbRes = as.factor(ifelse(str_detect(type, "Acinetobacter baumannii - res"), "pos", "neg")),
           KpRes = as.factor(ifelse(str_detect(type, "Klebsiella pneumoniae - res"), "pos", "neg")),
           AbSus = as.factor(ifelse(str_detect(type, "Acinetobacter baumannii - sen"), "pos", "neg")),
           KpSus = as.factor(ifelse(str_detect(type, "Klebsiella pneumoniae - sen"), "pos", "neg")))



trainIdx <- list(AbRes = list(idx = createDataPartition(specInfo$AbRes, p = 0.6, list = F),
                              regex = "Acinetobacter baumannii - res"),
                 KpRes = list(idx = createDataPartition(specInfo$KpRes, p = 0.6, list = F),
                              regex = "Klebsiella pneumoniae - res"),
                 AbSus = list(idx = createDataPartition(specInfo$AbSus, p = 0.6, list = F),
                              regex = "Acinetobacter baumannii - sen"),
                 KpSus = list(idx = createDataPartition(specInfo$KpSus, p = 0.6, list = F),
                              regex = "Klebsiella pneumoniae - sen"))

```

# Determine Features
```{r determineFeatures, cache = T}
determineFeatures <- function(trainList, n = 20) {
    # Preprocess spectra
    spec <- preProcessSpec(files[trainList$idx], hws = 80)
    multiSpecIdx <- map_lgl(spec, ~ metaData(.)$num > 1)
    spec <- spec[!multiSpecIdx]

    # Detect peaks
    peaks <- detectPeaks(spec, halfWindowSize = 80, SNR = 5)
    peaks <- binPeaks(peaks, tolerance = 0.5)
    
    # extract peaks
    peakDat <- extractPeaks(peaks, spec)
    
    # extract features
    features <- peakDat %>%
        mutate(sel = str_detect(type, trainList$regex)) %>%
        filter(sel) %>%
        group_by(sel, mz) %>%
        summarize(relInt = sum(relInt)) %>%
        group_by(sel) %>%
        mutate(relInt = relInt / max(relInt)) %>%
        arrange(desc(relInt)) %>%
        filter(relInt >= relInt[n]) %>%
        arrange(desc(mz))
    
    return(features)
}

featureList <- map(trainIdx, determineFeatures)
trainIdx$AbRes$features <- unique(featureList$AbRes$mz)
trainIdx$KpRes$features <- unique(featureList$KpRes$mz)
trainIdx$AbSus$features <- unique(featureList$AbSus$mz)
trainIdx$KpSus$features <- unique(featureList$KpSus$mz)

features <- tibble(response = names(featureList), featList = featureList) %>%
    unnest() %>%
    select(response, mz)

features <- unique(features)
saveRDS(features, file = "temp/features.RDS")
```

# Extract features from Spectra
```{r extractFeatures, cache = T}
createFeatureTbl <- function(trainList, mzTol, testSet = F) {
    idx <- if(testSet) -trainList$idx else trainList$idx
    suffix <- if(testSet) "_test" else "_train"
    suffix2 <- if(str_detect(trainList$regex, "Acineto")) "_Ab" else "_Kp"
    suffix3 <- if(str_detect(trainList$regex, "res")) "_res" else "_sus"
    
    # Preprocess spectra
    spec <- preProcessSpec(files[idx], hws = 80)
    multiSpecIdx <- map_lgl(spec, ~ metaData(.)$num > 1)
    spec <- spec[!multiSpecIdx]
    
    # extract spectra 
    spectbl <- map_df(spec, extractSpectra) %>% 
      mutate(type = as.factor(type), id = as.factor(id))
    
    # extract specified features
    feattbl <- spectbl %>%
      group_by(id) %>%
      do(extractFeatures(., featureVec = trainList$features, tol = mzTol))
    
    saveRDS(feattbl, file = paste0("temp/featureInfo", suffix2, suffix3, suffix))
    
    mlFeat <- feattbl %>%
      select(id, type, feat, relInt) %>%
      group_by(id) %>%
      mutate(relInt = relInt / max(relInt)) %>%
      ungroup() %>%
      spread(key = feat, value = relInt, fill = 0) %>%
      mutate(AbRes = as.factor(ifelse(str_detect(type, "i - r"), "pos", "neg")),
             KpRes = as.factor(ifelse(str_detect(type, "e - r"), "pos", "neg")),
             AbSus = as.factor(ifelse(str_detect(type, "i - s"), "pos", "neg")),
             KpSus = as.factor(ifelse(str_detect(type, "e - s"), "pos", "neg")))
    
    return(mlFeat)
}

trainDatList <- map(trainIdx, createFeatureTbl, 
                    mzTol = 2.5,
                    testSet = F)

```


# Model Tuning Parameters
```{r tuningParams}
# AUC of precision-recall curve
auprcSummary <- function(data, lev = NULL, model = NULL){
  
  index_class2 <- data$obs == "pos"
  index_class1 <- data$obs == "neg"
  
  the_curve <- PRROC::pr.curve(data$pos[index_class2],
                               data$pos[index_class1],
                               curve = FALSE)
  
  out <- the_curve$auc.integral
  names(out) <- "AUPRC"
  
  return(out)
  
}

# 10-fold CV
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                           summaryFunction = auprcSummary,
                           classProbs = T,
                           sampling = "up")
```

# Fitting Ab models
```{r AbModel, cache = T}
AbResResponse <- trainDatList$AbRes %>% select(AbRes)
AbResVars <- trainDatList$AbRes %>% select(starts_with("mz"))

AbResTune <- train(x = AbResVars,
                y = AbResResponse$AbRes,
                method = "rf",
                trControl = fitControl,
                metric = "AUPRC")


AbSusResponse <- trainDatList$AbSus %>% select(AbSus)
AbSusVars <- trainDatList$AbSus %>% select(starts_with("mz"))

AbSusTune <- train(x = AbSusVars,
                y = AbSusResponse$AbSus,
                method = "rf",
                trControl = fitControl,
                metric = "AUPRC")
```

# Fitting Kp models
```{r KpModel, cache = T}
KpResResponse <- trainDatList$KpRes %>% select(KpRes)
KpResVars <- trainDatList$KpRes %>% select(starts_with("mz"))

KpResTune <- train(x = KpResVars,
                y = KpResResponse$KpRes,
                method = "rf",
                trControl = fitControl,
                metric = "AUPRC")


KpSusResponse <- trainDatList$KpSus %>% select(KpSus)
KpSusVars <- trainDatList$KpSus %>% select(starts_with("mz"))

KpSusTune <- train(x = KpSusVars,
                y = KpSusResponse$KpSus,
                method = "rf",
                trControl = fitControl,
                metric = "AUPRC")
```

# Save Models
```{r saveModels}
modelList <- list(AbResTune, AbSusTune, KpResTune, KpSusTune)

saveRDS(modelList, file = "results/modelList")

```


# Generate Test Sets
```{r generateTestSets}
testDatList <- map(trainIdx, createFeatureTbl, 
                    mzTol = 2.5,
                    testSet = T)

saveRDS(testDatList, file = "temp/testDatList.RDS")
```

